name: Tests

on: [push, pull_request]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: 22

      - name: Install deps
        run: pnpm i --frozen-lockfile

      - name: Build
        run: yarn run build

      - name: Run ESLint & Prettier
        run: yarn run lint
